main: me.citizensplaceholderapi.CitizensPlaceholderAPI
version: ${pluginVersion}
name: CitizensPlaceholderAPI
depend: [PlaceholderAPI, Citizens]
author: TheGaming999 & MineArcade Development Team
commands:
  citizensplaceholderapi:
    usage: /<command>
    description: The main command for this plugin
    aliases: [citizenspapi, cpapi, cplaceholderapi, npcpapi, npcplaceholderapi]